# Generated by Django 5.1 on 2024-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_commoditydata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='buffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Commodity', models.CharField(max_length=50)),
            ],
        ),
    ]
