# Generated by Django 5.1 on 2024-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_buffer_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commodity', models.CharField(max_length=50)),
                ('stock', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='buffer',
        ),
    ]
