# Generated by Django 5.1 on 2024-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_bufferstock_delete_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferstock',
            name='threshold',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bufferstock',
            name='Commodity',
            field=models.CharField(max_length=100),
        ),
    ]
