# Generated by Django 5.1 on 2024-09-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_bufferstock_threshold_alter_bufferstock_commodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditydata',
            name='District',
        ),
    ]
